### ISSUE TITLE
Create a Postgres instance and db for RUCIO

### ISSUE THREAD

**Issue by egazzarr** [EOSC-Future/eosc-future-cern#15]
Request a new [CERN DBOD](dbod.web.cern.ch/) Postgres instance for all future databases in this project.

**Comment by goseind** [comment]
A database with the name `vre` was created and modified as follows:

```bash
psql -h <ip-alias> -p <port> -U admin -c '\password'
CREATE USER rucio WITH PASSWORD '';
CREATE DATABASE rucio;
GRANT ALL PRIVILEGES ON DATABASE rucio TO rucio;
```

The passwords for both users are stored in `tbag`.

Further, the line `host rucio rucio 0.0.0.0/0 md5` had to be added to the`pg_hba.conf` file in order to allow connections with that user. Changes are tracked in the DBOD WebUI.

- [ ] Create a db secret for rucio according to: https://rucio.cern.ch/documentation/database/

**Comment by goseind** [comment]
A new database instance called `vre` has been created.

Passwords have been stored in tbag:

* `dbod_vre_user_admin`
* `dbod_vre_user_rucio`

and dbconnect string is stored as a secret in the cluster, so it can be accessed by terraform for example:

```
set {
    name = "config.database.default"
    value = data.kubernetes_secret_v1.rucio_db_secret.data.dbconnectstring
  }
}
```
